// Available academic interests
export const academicInterests = [
	"Arts",
	"Biology",
	"Business",
	"Computer Science",
	"Economics",
	"Engineering",
	"Finance",
	"Health Sciences",
	"Humanities",
	"Mathematics",
	"Medicine",
	"Social Sciences",
	"Technology",
];

// US Regions
export const regions = ["Northeast", "Southeast", "Midwest", "Southwest", "West Coast", "Northwest", "Other"];

// Available graduation years (current year + 1-4 years)
export const getGraduationYears = (): number[] => {
	const currentYear = new Date().getFullYear();
	return [
		currentYear,
		currentYear + 1,
		currentYear + 2,
		currentYear + 3,
		currentYear + 4,
		currentYear + 5,
		currentYear + 6,
		currentYear + 7,
	];
};

// Grade-specific milestone data
export const milestones = {
	"Freshman (9th Grade)": {
		academics: [
			"Take challenging core courses",
			"Identify subjects that interest you",
			"Develop good study habits",
			"Meet with your school counselor",
		],
		extracurricular: [
			"Explore clubs and activities",
			"Try different sports or arts programs",
			"Consider volunteer opportunities",
			"Start tracking your activities",
		],
		collegePrep: [
			"Start thinking about potential careers",
			"Talk to adults about their college experiences",
			"Research high school course requirements for college",
			"Create an academic four-year plan",
		],
	},
	"Sophomore (10th Grade)": {
		academics: [
			"Take the PSAT for practice",
			"Consider AP or honors courses",
			"Maintain a strong GPA",
			"Identify academic strengths",
		],
		extracurricular: [
			"Deepen involvement in activities",
			"Consider leadership opportunities",
			"Continue community service",
			"Participate in summer programs",
		],
		collegePrep: [
			"Research college types and majors",
			"Attend college fairs",
			"Visit nearby campuses if possible",
			"Start preparing for standardized tests",
		],
	},
	"Junior (11th Grade)": {
		academics: [
			"Take challenging courses relevant to your interests",
			"Prepare for and take the SAT/ACT",
			"Consider SAT Subject Tests",
			"Maintain strong academic performance",
		],
		extracurricular: [
			"Take on leadership roles",
			"Focus on meaningful involvement",
			"Seek internship opportunities",
			"Consider summer programs related to your interests",
		],
		collegePrep: [
			"Build your college list",
			"Research financial aid and scholarships",
			"Visit colleges",
			"Prepare for college essays",
			"Talk to teachers about recommendation letters",
		],
	},
	"Senior (12th Grade)": {
		academics: [
			"Maintain strong grades",
			"Take any remaining standardized tests",
			"Complete challenging courses",
			"Avoid senioritis",
		],
		extracurricular: [
			"Continue leadership positions",
			"Document achievements and hours",
			"Consider mentoring younger students",
			"Engage with your community",
		],
		collegePrep: [
			"Complete college applications",
			"Submit financial aid forms (FAFSA/CSS Profile)",
			"Apply for scholarships",
			"Consider early decision/action options",
			"Make final college decision",
			"Prepare for transition to college",
		],
	},
	"Middle School": {
		academics: [
			"Build strong academic foundations",
			"Develop good study habits",
			"Read widely across subjects",
			"Learn about different high school options",
		],
		extracurricular: [
			"Try different activities to discover interests",
			"Participate in school clubs",
			"Consider community activities",
			"Keep a log of activities",
		],
		collegePrep: [
			"Start thinking about potential interests",
			"Research high school course options",
			"Talk to parents and teachers about college planning",
			"Visit a local college campus for exposure",
		],
	},
	"College/Graduate": {
		academics: [
			"Focus on your studies or career",
			"Consider advanced degrees if relevant",
			"Maintain professional development",
			"Network in your field",
		],
		extracurricular: [
			"Engage in professional organizations",
			"Volunteer in your community",
			"Develop leadership skills",
			"Build your professional portfolio",
		],
		collegePrep: [
			"Explore career opportunities",
			"Research graduate programs if interested",
			"Connect with professionals in your field",
			"Develop job-seeking skills",
		],
	},
};

// lib/data.ts

export const competitionsData = [
	{
		title: "Science Olympiad",
		description:
			"A team-based competition in various science disciplines including engineering, biology, and social sciences.",
		tags: ["Engineering", "Computer Science", "Biology", "Mathematics", "Social Sciences"],
		organization: "National Science Olympiad Organization",
		registrationLink: "https://www.soinc.org/",
		infoLink: "https://www.soinc.org/",
	},
	{
		title: "Intel International Science and Engineering Fair (ISEF)",
		description:
			"A prestigious science fair for students to present independent research in areas like biology, medicine, and engineering.",
		tags: ["Biology", "Engineering", "Computer Science", "Medicine"],
		organization: "Intel Foundation",
		registrationLink: "https://www.societyforscience.org/isef/",
		infoLink: "https://www.societyforscience.org/isef/",
	},
	{
		title: "Business Professionals of America (BPA)",
		description: "A competition in business-related fields like finance, economics, and management.",
		tags: ["Business", "Finance", "Economics"],
		organization: "Business Professionals of America Organization",
		registrationLink: "https://www.bpa.org/",
		infoLink: "https://www.bpa.org/",
	},
	{
		title: "Google Code-In",
		description:
			"A global coding competition for pre-university students, where participants contribute to open source software.",
		tags: ["Computer Science", "Technology"],
		organization: "Google",
		registrationLink: "https://developers.google.com/open-source/gci",
		infoLink: "https://developers.google.com/open-source/gci",
	},
	{
		title: "Model United Nations (MUN)",
		description:
			"A simulation of the UN, where students debate global issues from political, economic, and social perspectives.",
		tags: ["Social Sciences", "Humanities", "Economics"],
		organization: "MUN International Organizations",
		registrationLink: "https://www.mun.org/",
		infoLink: "https://www.mun.org/",
	},
	{
		title: "HOSA-Future Health Professionals",
		description:
			"A competition for students interested in health professions, focusing on medical knowledge and healthcare-related skills.",
		tags: ["Health Sciences", "Medicine"],
		organization: "HOSA International",
		registrationLink: "https://www.hosa.org/",
		infoLink: "https://www.hosa.org/",
	},
	{
		title: "American Mathematics Competitions (AMC)",
		description:
			"A series of math competitions for high school students, focusing on problem-solving and mathematical theory.",
		tags: ["Mathematics"],
		organization: "Mathematical Association of America",
		registrationLink: "https://www.maa.org/math-competitions",
		infoLink: "https://www.maa.org/math-competitions",
	},
	{
		title: "The Economics Challenge",
		description:
			"A national competition where students demonstrate their knowledge of economics through various rounds of questions and challenges.",
		tags: ["Economics", "Business"],
		organization: "Council for Economic Education",
		registrationLink: "https://www.councilforeconed.org/",
		infoLink: "https://www.councilforeconed.org/",
	},
	{
		title: "FIRST Robotics",
		description:
			"An engineering competition where students design and build robots to compete in various challenges.",
		tags: ["Engineering", "Computer Science", "Technology"],
		organization: "FIRST Robotics",
		registrationLink: "https://www.firstinspires.org/robotics",
		infoLink: "https://www.firstinspires.org/robotics",
	},
	{
		title: "National History Day",
		description:
			"A history-based competition where students research and present historical topics through papers, exhibits, websites, and documentaries.",
		tags: ["Humanities", "Social Sciences"],
		organization: "National History Day Organization",
		registrationLink: "https://www.nhd.org/",
		infoLink: "https://www.nhd.org/",
	},
];

// cities
export const cityList = [
	"New York, New York",
	"Los Angeles, California",
	"Chicago, Illinois",
	"Houston, Texas",
	"Phoenix, Arizona",
	"Philadelphia, Pennsylvania",
	"San Antonio, Texas",
	"San Diego, California",
	"Dallas, Texas",
	"Jacksonville, Florida",
	"Fort Worth, Texas",
	"Austin, Texas",
	"San Jose, California",
	"Charlotte, North Carolina",
	"Columbus, Ohio",
	"Indianapolis, Indiana",
	"San Francisco, California",
	"Seattle, Washington",
	"Denver, Colorado",
	"Oklahoma City, Oklahoma",
	"Nashville, Tennessee",
	"Washington, District of Columbia",
	"El Paso, Texas",
	"Las Vegas, Nevada",
	"Boston, Massachusetts",
	"Detroit, Michigan",
	"Portland, Oregon",
	"Louisville/Jefferson County, Kentucky",
	"Memphis, Tennessee",
	"Baltimore, Maryland",
	"Albuquerque, New Mexico",
	"Milwaukee, Wisconsin",
	"Tucson, Arizona",
	"Fresno, California",
	"Sacramento, California",
	"Atlanta, Georgia",
	"Mesa, Arizona",
	"Kansas City, Missouri",
	"Colorado Springs, Colorado",
	"Raleigh, North Carolina",
	"Omaha, Nebraska",
	"Miami, Florida",
	"Virginia Beach, Virginia",
	"Long Beach, California",
	"Oakland, California",
	"Minneapolis, Minnesota",
	"Bakersfield, California",
	"Tulsa, Oklahoma",
	"Tampa, Florida",
	"Arlington, Texas",
	"Aurora, Colorado",
	"Wichita, Kansas",
	"Cleveland, Ohio",
	"New Orleans, Louisiana",
	"Henderson, Nevada",
	"Honolulu, Hawaii",
	"Anaheim, California",
	"Orlando, Florida",
	"Riverside, California",
	"Lexington, Kentucky",
	"Stockton, California",
	"Irvine, California",
	"Corpus Christi, Texas",
	"Cincinnati, Ohio",
	"Santa Ana, California",
	"Greensboro, North Carolina",
	"Pittsburgh, Pennsylvania",
	"Newark, New Jersey",
	"St. Paul, Minnesota",
	"Durham, North Carolina",
	"Lincoln, Nebraska",
	"North Las Vegas, Nevada",
	"Jersey City, New Jersey",
	"Plano, Texas",
	"Anchorage, Alaska",
	"Madison, Wisconsin",
	"Chandler, Arizona",
	"Reno, Nevada",
	"Gilbert, Arizona",
	"St. Louis, Missouri",
	"Chula Vista, California",
	"Buffalo, New York",
	"Fort Wayne, Indiana",
	"Lubbock, Texas",
	"St. Petersburg, Florida",
	"Toledo, Ohio",
	"Laredo, Texas",
	"Port St. Lucie, Florida",
	"Glendale, Arizona",
	"Chesapeake, Virginia",
	"Winston-Salem, North Carolina",
	"Irving, Texas",
	"Scottsdale, Arizona",
	"Garland, Texas",
	"Enterprise, Nevada",
	"Arlington, Virginia",
	"Boise, Idaho",
	"Cape Coral, Florida",
	"Frisco, Texas",
	"Richmond, Virginia",
	"Spokane, Washington",
	"Norfolk, Virginia",
	"Huntsville, Alabama",
	"Fremont, California",
	"San Bernardino, California",
	"Tacoma, Washington",
	"Spring Valley, Nevada",
	"Santa Clarita, California",
	"Hialeah, Florida",
	"Modesto, California",
	"McKinney, Texas",
	"Fontana, California",
	"Baton Rouge, Louisiana",
	"Moreno Valley, California",
	"Salt Lake City, Utah",
	"Sioux Falls, South Dakota",
	"Fayetteville, North Carolina",
	"Des Moines, Iowa",
	"Worcester, Massachusetts",
	"Yonkers, New York",
	"Rochester, New York",
	"Little Rock, Arkansas",
	"Grand Prairie, Texas",
	"Tallahassee, Florida",
	"Amarillo, Texas",
	"Peoria, Arizona",
	"Augusta-Richmond County, Georgia",
	"Knoxville, Tennessee",
	"Columbus, Georgia",
	"Sunrise Manor, Nevada",
	"Vancouver, Washington",
	"Oxnard, California",
	"Overland Park, Kansas",
	"Grand Rapids, Michigan",
	"Birmingham, Alabama",
	"Montgomery, Alabama",
	"Tempe, Arizona",
	"Brownsville, Texas",
	"Providence, Rhode Island",
	"Huntington Beach, California",
	"Paradise, Nevada",
	"Chattanooga, Tennessee",
	"Akron, Ohio",
	"Clarksville, Tennessee",
	"Fort Lauderdale, Florida",
	"Ontario, California",
	"Glendale, California",
	"Newport News, Virginia",
	"Cary, North Carolina",
	"Mobile, Alabama",
	"Elk Grove, California",
	"Eugene, Oregon",
	"Salem, Oregon",
	"Aurora, Illinois",
	"Santa Rosa, California",
	"Shreveport, Louisiana",
	"Rancho Cucamonga, California",
	"Pembroke Pines, Florida",
	"Springfield, Missouri",
	"Fort Collins, Colorado",
	"Murfreesboro, Tennessee",
	"Oceanside, California",
	"Garden Grove, California",
	"Denton, Texas",
	"Lancaster, California",
	"Surprise, Arizona",
	"Roseville, California",
	"Killeen, Texas",
	"Corona, California",
	"Palmdale, California",
	"Salinas, California",
	"Charleston, South Carolina",
	"Macon-Bibb County, Georgia",
	"Lakewood, Colorado",
	"Paterson, New Jersey",
	"Hollywood, Florida",
	"Alexandria, Virginia",
	"Hayward, California",
	"Springfield, Massachusetts",
	"Kansas City, Kansas",
	"Bellevue, Washington",
	"Sunnyvale, California",
	"Joliet, Illinois",
	"Naperville, Illinois",
	"Olathe, Kansas",
	"Bridgeport, Connecticut",
	"McAllen, Texas",
	"Savannah, Georgia",
	"Escondido, California",
	"Gainesville, Florida",
	"Mesquite, Texas",
	"Waco, Texas",
	"Visalia, California",
	"Thornton, Colorado",
	"Rockford, Illinois",
	"Syracuse, New York",
	"Pasadena, Texas",
	"Columbia, South Carolina",
	"Pomona, California",
	"Palm Bay, Florida",
	"Jackson, Mississippi",
	"Victorville, California",
	"Midland, Texas",
	"Meridian, Idaho",
	"Miramar, Florida",
	"Metairie, Louisiana",
	"Orange, California",
	"Fullerton, California",
	"New Haven, Connecticut",
	"Hampton, Virginia",
	"Torrance, California",
	"Stamford, Connecticut",
	"Lewisville, Texas",
	"Warren, Michigan",
	"Fargo, North Dakota",
	"Elizabeth, New Jersey",
	"Cedar Rapids, Iowa",
	"Coral Springs, Florida",
	"Dayton, Ohio",
	"Round Rock, Texas",
	"Sterling Heights, Michigan",
	"Carrollton, Texas",
	"West Valley City, Utah",
	"Kent, Washington",
	"Pasadena, California",
	"Santa Clara, California",
	"Norman, Oklahoma",
	"Columbia, Missouri",
	"Abilene, Texas",
	"Athens-Clarke County, Georgia",
	"Pearland, Texas",
	"Clovis, California",
	"College Station, Texas",
	"West Palm Beach, Florida",
	"Topeka, Kansas",
	"Lakeland, Florida",
	"Wilmington, North Carolina",
	"Simi Valley, California",
	"Allentown, Pennsylvania",
	"Lehigh Acres, Florida",
	"North Charleston, South Carolina",
	"Rochester, Minnesota",
	"Thousand Oaks, California",
	"The Woodlands, Texas",
	"Billings, Montana",
	"Vallejo, California",
	"Lafayette, Louisiana",
	"Concord, California",
	"Fairfield, California",
	"Broken Arrow, Oklahoma",
	"Arvada, Colorado",
	"Independence, Missouri",
	"Spring Hill, Florida",
	"Hartford, Connecticut",
	"Nampa, Idaho",
	"Cambridge, Massachusetts",
	"Ann Arbor, Michigan",
	"Antioch, California",
	"High Point, North Carolina",
	"New Braunfels, Texas",
	"Berkeley, California",
	"League City, Texas",
	"Menifee, California",
	"Richardson, Texas",
	"Clearwater, Florida",
	"Goodyear, Arizona",
	"Odessa, Texas",
	"Las Cruces, New Mexico",
	"Manchester, New Hampshire",
	"Waterbury, Connecticut",
	"Evansville, Indiana",
	"Westminster, Colorado",
	"West Jordan, Utah",
	"Pompano Beach, Florida",
	"Brandon, Florida",
	"Buckeye, Arizona",
	"East Los Angeles, California",
	"Conroe, Texas",
	"Lowell, Massachusetts",
	"Greeley, Colorado",
	"Tuscaloosa, Alabama",
	"Allen, Texas",
	"Richmond, California",
	"Carlsbad, California",
	"Elgin, Illinois",
	"Provo, Utah",
	"Rio Rancho, New Mexico",
	"Murrieta, California",
	"Lansing, Michigan",
	"Springfield, Illinois",
	"Concord, North Carolina",
	"South Fulton, Georgia",
	"Tyler, Texas",
	"Beaumont, Texas",
	"Everett, Washington",
	"Temecula, California",
	"Pueblo, Colorado",
	"Sparks, Nevada",
	"Miami Gardens, Florida",
	"Santa Maria, California",
];
